---
title: "11_Deployments_Table_Field_Definitions"
format: html
---

## Deployments Table Field Definitions

**Filename: deployments.csv**

Below are the field definitions for the Deployments table, which is a primary table.

+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+-------------+---------------+---------------------------+----------------------------+
| **Field**             | **Definition**                                                                                                                                            | **Required**      | **Default** | **Data Type** | **Reference Table**       | **Constraint**             |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+-------------+---------------+---------------------------+----------------------------+
| **organization_code** | Code for the organization that owns the deployment                                                                                                        | Always            |             | Code          | Organizations (see Excel) |                            |
|                       |                                                                                                                                                           |                   |             |               |                           |                            |
|                       | \                                                                                                                                                         |                   |             |               |                           |                            |
|                       |                                                                                                                                                           |                   |             |               |                           |                            |
|                       | Examples: "NEFSC", "WHOI"                                                                                                                                 |                   |             |               |                           |                            |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+-------------+---------------+---------------------------+----------------------------+
| **deployment_code**   | Unique code for the deployment. The recommendation is to use \[organization_code\]\_\[project_region_code\]\_\[YYYYMM\]\_\[site_code\].                   | Always            |             | Code          |                           | Unique within organization |
|                       |                                                                                                                                                           |                   |             |               |                           |                            |
|                       | \                                                                                                                                                         |                   |             |               |                           |                            |
|                       |                                                                                                                                                           |                   |             |               |                           |                            |
|                       | Examples: "WHOI_GOM_202310_WE03", "WHOI_MA-RI_202210_WE16", "NEFSC_MA-RI_202110_NS01", "NEFSC_MA-RI_202202_COX02"                                         |                   |             |               |                           |                            |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+-------------+---------------+---------------------------+----------------------------+
| **project_code**      | Code of the project that the deployment belongs to. Only need to create a project code if there are multiple deployments that should be grouped together. | Required for NCEI |             | Code          | Projects                  |                            |
|                       |                                                                                                                                                           |                   |             |               |                           |                            |
|                       | \                                                                                                                                                         |                   |             |               |                           |                            |
|                       |                                                                                                                                                           |                   |             |               |                           |                            |
|                       | Examples: "WHOI_GOM_202310", "NEFSC_MA-RI_202202"                                                                                                         |                   |             |               |                           |                            |
+-----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+-------------+---------------+---------------------------+----------------------------+
