---
title: "Detections Table Field Definitions"
format: html
---

**Filename: detections.csv**

Below are the field definitions for the Detections table, which is a primary table.

+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **Field**                          | **Definition**                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | **Required**                             | **Default** | **Data Type** | **Reference Table**                    | **Constraint** |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **deployment_organization_code**   | Code of the organization that the deployment belongs to.                                                                                                                                                                                                                                                                                                                                                                                                                                                                             | Always                                   |             | Code          | Organizations (see Excel)              |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "NEFSC", "WHOI"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **deployment_code**                | Unique code for the deployment that the analysis belongs to.                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Always                                   |             | Code          | Deployments                            |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "WHOI_GOM_202310_WE03", "WHOI_MA-RI_202210_WE16", "NEFSC_MA-RI_202110_NS01", "NEFSC_MA-RI_202202_COX02"                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **analysis_organization_code**     | Code of the organization that conducted and owns the analysis.                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Always                                   |             | Code          | Organizations (see Excel)              |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "NEFSC", "WHOI"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **analysis_code**                  | Code of the analysis that the detection belongs to.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Always                                   |             | Code          | Analyses                               |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "RIWH_ANALYSIS", "BEAKED_ANALYSIS"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_start_datetime**       | Start date and time for the time period for the detection event or time bin depending on analysis granularity                                                                                                                                                                                                                                                                                                                                                                                                                        | Always                                   |             | Timestamp     |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "2025-03-26T15:34:27-0500"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_end_datetime**         | End date and time for the time period for the detection event or time bin depending on analysis granularity. If detection is for a single point in time, the start and end datetimes can be the same.                                                                                                                                                                                                                                                                                                                                | Always                                   |             | Timestamp     |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "2025-03-26T15:34:27-0500", "2025-03-26T15:34:30-0500"                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_effort_secs**          | The amount of time (in seconds) the effort occurred in. This would translate to encounter or event duration for encounter/event level data. If the entire period was analyzed, enter total duration between the detection start and end datetimes.                                                                                                                                                                                                                                                                                   | Always                                   |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: If the first 5 minutes of every hourly analysis bin was analyzed, this number would be "300". If the full hour of every hourly analysis bin was analyzed, this number would be "3600".                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_sound_source_code**    | The species or detected sound the detection period relates to                                                                                                                                                                                                                                                                                                                                                                                                                                                                        | Always                                   |             | Code          | Sound Sources (see Excel)              |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "HUWH", "STDO", "RV-L", "RAIN"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_call_type_code**       | The call/click type used for presence determination for the detection period                                                                                                                                                                                                                                                                                                                                                                                                                                                         | Always                                   |             | Code          | Call Types (see Excel)                 |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "RIWH_UPCALL", "HUWH_SONG", "OD_WHIS_HF"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_behavior_code**        | Behavior associated with detected event                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                                          |             | Code          | Behaviors (see Excel)                  |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "CONTACT", "FORAGING", "MOM_CALF", "MATING"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_demographic_code**     | The demographic determined of the sound source for the detection period                                                                                                                                                                                                                                                                                                                                                                                                                                                              |                                          |             | Code          | Demographics (see Excel)               |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "ADULT_FEMALE_OR_JUV", "MID-SIZED_INDIVIDUAL", "MIXED_GROUP"                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_n_validated**          | Number of actual detections that have been validated to be correct in the detection time period                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             | Integer       |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "3", "258"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_n_total**              | Total number of detections for the sound source within the detection time period (can include true and false detections)                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             | Integer       |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "15", "179"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_result_code**          | Detection result indicating if the species was detected or not                                                                                                                                                                                                                                                                                                                                                                                                                                                                       | Always                                   |             | Code          | Detection Result Types (see Excel)     |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "DETECTED", "POSSIBLY_DETECTED", "NOT_DETECTED"                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_event_type**           | Type of detection event (if available)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |                                          |             | Text          |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: PAMGuard's eventType field                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_event_id**             | ID of the detection event (if available)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             | Text          |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: PAMGuard's event ID                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_latitude**             | Latitude of the platform location at time of detection (or start of encounter) in decimal degrees (DD.DDDD), only applicable to mobile platforms (e.g., gliders, buoys)                                                                                                                                                                                                                                                                                                                                                              |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "41.141289"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_longitude**            | Longitude of the platform location at time of detection (or start of encounter) in decimal degrees (DD.DDDD), only applicable to mobile platforms (e.g., gliders, buoys). Negative for locations west of the central meridian.                                                                                                                                                                                                                                                                                                       |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "-71.102908"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_received_level_db**    | Received level of the detection in dB. For single call detections, a singular value should be placed here. For encounters or time binned data, an average or median received level should be placed here. Further details such as the exact unit (e.g. dB RMS, or dB pp), and whether a median or average received level was used should be placed in the analysis_json or analysis_comments fields of the parent analysis. For encounters/time binned data, each signal's received level can be placed in the detection_json field. |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "15"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_quality_code**         | Quality type of the detection if it was validated or not. This field may be left blank if the analysis_quality_code is "UNKNOWN" for the parent analysis, otherwise it is recommended to fill it out.                                                                                                                                                                                                                                                                                                                                |                                          |             | Code          | Detection Quality Types (see Excel)    |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "INVALID", "UNVERIFIED", "VALID", "PARTIALLY_VALID"                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_n_animals**            | Estimated number of animals thought to be in the detection                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |                                          |             | Integer       |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "25"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_n_animals_min**        | Minimum number of animals thought to be in the detection                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             | Integer       |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "1"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_n_animals_max**        | Maximum number of animals thought to be in the detection                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             | Integer       |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "3"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_json**                 | Additional structured data about the detection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                          |             | JSON          |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **detection_comments**             | Comments about the detection                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                          |             | Text          |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_method_code**       | Method used to localize the position of the animal(s)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | Required if submitting localization data |             | Code          | Localization Methods (see Excel)       |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "3D_SIMPLEX", "DMON_REAL-TIME", "SHIP-POSITION"                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_latitude**          | Estimated localized latitude of the animal in decimal degrees (DD.DDDDDD)                                                                                                                                                                                                                                                                                                                                                                                                                                                            |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "41.141289"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_latitude_min**      | Minimum localized latitude accounting for localization uncertainty in decimal degrees (DD.DDDDDD)                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "40.724307"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_latitude_max**      | Maximum localized latitude accounting for localization uncertainty in decimal degrees (DD.DDDDDD)                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "41.141289"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_longitude**         | Estimates localized longitude of the animal in decimal degrees (DD.DDDDDD), negative for locations west of the central meridian                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "-71.102908"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_longitude_min**     | Minimum localized longitude accounting for localization uncertainty in decimal degrees (DD.DDDDDD), negative for locations west of the central meridian                                                                                                                                                                                                                                                                                                                                                                              |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "-70.016567"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_longitude_max**     | Maximum localized longitude accounting for localization uncertainty in decimal degrees (DD.DDDDDD), negative for locations west of the central meridian                                                                                                                                                                                                                                                                                                                                                                              |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "-71.102908"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_distance_m**        | Estimated range of detection (in meters) from the recording platform                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "3", "60.5"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_distance_m_min**    | Minimum range of detection (in meters) from the recording platform                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "0"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_distance_m_max**    | Maximum range of detection (in meters) from the recording platform                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "8047"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_bearing**           | For beamforming, the estimated bearing angle of the localization cone (0-360 degrees). Specify if bearing is measured relative to true north, magnetic north, or device orientation, and compass rose convention (clockwise, counter-clockwise) in analysis_json or analysis_comments.                                                                                                                                                                                                                                               |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "170", "170.5"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_bearing_min**       | For beamforming, the start bearing angle of the localization cone (0-360 degrees)                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "167", "167.5"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_bearing_max**       | For beamforming, the end bearing angle of the localization cone (0-360 degrees)                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "175", "175.34"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_depth_method_code** | Method used to estimate depth of the animal(s)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                          |             | Code          | Localization Depth Methods (see Excel) |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "3D_TDOA", "MANUAL_DRTD", "WHALEDO"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_depth_n_signals**   | Number of signals used to derive the depth                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |                                          |             | Integer       |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "7", "218"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_depth_m**           | Estimated depth of animal (in meters)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Examples: "5", "28.6"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_depth_m_min**       | Minimum depth of animal (in meters)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "1.5"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_depth_m_max**       | Maximum depth of animal (in meters)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |                                          |             | Float         |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | \                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |                                          |             |               |                                        |                |
|                                    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             |               |                                        |                |
|                                    | Example: "893"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |                                          |             |               |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_json**              | Additional structured data about localization in JSON format                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |                                          |             | JSON          |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
| **localization_comments**          | Comments about the localization                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |                                          |             | Text          |                                        |                |
+------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------+-------------+---------------+----------------------------------------+----------------+
