---
title: "2_Document_History_and_Revisions"
format: html
---

## Document History and Revisions

+-------------+-----------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Version** | **Date**        | **Author**      | **Description**                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
+-------------+-----------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **1.0**     | May 1, 2025     | Julianne Wilder | Document Created                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------------+-----------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **1.1**     | June 10, 2025   | Jeffrey Walker  | Updated “Data Table Template Instructions” to clarify that filenames and folder structure must match “templates” sub-directory.                                                                                                                                                                                                                                                                                                                                                     |
+-------------+-----------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **1.2**     | August 26, 2025 | Jeffrey Walker  | -   Renamed the **organization_code** to **deployment_organization_code** in the analyses and detections tables to clarify that this field refers to the organization that owns the deployment. Also added **analysis_organization_code** to the detections table. Both tables now include both the **deployment_organization_code** (organization that the deployment and recording(s) belong to), and **analysis_organization_code** (organization that the analysis belongs to). |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Added **track_uri** to tracks table for linking tracks to external files in cloud storage (useful for linking track metadata to high resolution data not stored in makara)                                                                                                                                                                                                                                                                                                      |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Fixed minor typos                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
+-------------+-----------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **1.3**     | October 7, 2025 | Jeffrey Walker  | -   Clarified that deployments, recordings, analyses and detections are the primary data tables, but not always required for each submission                                                                                                                                                                                                                                                                                                                                        |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Added **Sensor Datasets** and **Sensor Values** templates                                                                                                                                                                                                                                                                                                                                                                                                                       |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Added **deployment_realtime** and **deployment_url** fields                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Updated **JSON** guidelines and examples                                                                                                                                                                                                                                                                                                                                                                                                                                        |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Set default value for **recording_n_channels** to 1                                                                                                                                                                                                                                                                                                                                                                                                                             |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Fixed **analysis_processing_types** to have values of POST_PROCESSEDandREAL_TIME(underscores instead of dashes)                                                                                                                                                                                                                                                                                                                                                                 |
|             |                 |                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
|             |                 |                 | -   Clarified descriptions of **analysis_release_data** and **analysis_release_pacm**                                                                                                                                                                                                                                                                                                                                                                                               |
+-------------+-----------------+-----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
