---
title: "Data Table Template Instructions"
format: html
---

To submit data and metadata to the Makara database, the information must be organized into template tables. The data template tables and example tables are provided in a downloadable zipped folder on the [Passive Acoustic Reporting System Templates](https://www.fisheries.noaa.gov/resource/document/passive-acoustic-reporting-system-templates) webpage, and are described in more detail below. Some of the tables are required, but do not necessarily need to be submitted at the same time. Other tables are optional, but it is highly recommended that the data contributor fills out any tables that are applicable to their deployment(s). Within each table, there are required and optional (but recommended if applicable) fields. The required tables/fields are the bare minimum of what metadata should be submitted. 

Within the template zipped folder is a sub-directory named “templates/”. This sub-directory contains empty CSV files that can be used as starting templates for filling out each table. Each data submission should contain one or more of these CSV files with data rows properly entered based on the formats described below. The names of each CSV file as well as the folder structure must match what is in the templates folder. Data cannot be submitted as an Excel Workbook (\*.xlsx file).
